### ISSUE TITLE
Take secrets from environment variables

### ISSUE THREAD

**Issue by daurnimator** [google/alertmanager-irc-relay#8]
We'd like to run this as a pod in kubernetes; with the base configuration in a configmap, but secrets in a secret.
Could you provide a way to configure secret via environment variable? Options include:

  - Have environment variables override any configuration field
  - Allow config file values to contain references to environment variables, e.g. `$NICKSERV_PASSWORD`

**Comment by shammash** [comment]
Hi, 

Thank you for suggesting this feature.

Commit aa63009ab4a925d6b1edc1a962ab9c46963d4c4d adds support for referencing environment variables in the config file.

I did not choose to override every config field (e.g. using https://github.com/kelseyhightower/envconfig ), because I suspect that the values specified via the environment will be very few (secrets and runtime parameters such as the port), and because specifying nested values such as the irc channel password would have required complex structures within the environment variables.

I believe the commit above addresses the feature request, so I am going to close this issue. Please feel free to reopen if that is not the case.

Thank you,

Luca
